Added upgrade script and dev install script for fedora. Minor cleanup in debian upgrade script and arch install scripts.

diff --git a/arch-install-dev-cpp-python-qt b/arch-install-dev-cpp-python-qt
--- a/arch-install-dev-cpp-python-qt
+++ b/arch-install-dev-cpp-python-qt
@@ -22,7 +22,7 @@
 #
 
 echo "Updating package database, upgrading existing packages, and installing new packages..."
-sudo pacman --sync --refresh --sysupgrade --needed "$@" \
+if ! sudo pacman --sync --refresh --sysupgrade --needed "$@" \
     `# Diff command` \
     diffutils \
     `# SSL toolkit (is also dependency of openssh, git and others)` \
@@ -41,7 +41,7 @@ sudo pacman --sync --refresh --sysupgrade --needed "$@" \
     python-pytest \
     ipython \
     pyside2 \
-    `# Boost headers and libraries (includes dependency boost-libs which is also dependency of gcc via source-highlight` \
+    `# Boost headers and libraries (includes dependency boost-libs which is also dependency of gcc via source-highlight)` \
     boost \
     `# Ninja build-system` \
     ninja \
@@ -51,6 +51,10 @@ sudo pacman --sync --refresh --sysupgrade --needed "$@" \
     gcc \
     `# GDB debugger` \
     gdb
+then
+    echo "Failed!"
+    exit 1
+fi
 
 # Possible additions
 #    `# Git client LFS extension (not used for now)` \
diff --git a/arch-install-dev-go b/arch-install-dev-go
--- a/arch-install-dev-go
+++ b/arch-install-dev-go
@@ -18,7 +18,7 @@
 #
 
 echo "Updating package database, upgrading existing packages, and installing new packages..."
-sudo pacman --sync --refresh --sysupgrade --needed "$@" \
+if ! sudo pacman --sync --refresh --sysupgrade --needed "$@" \
     `# Diff command` \
     diffutils \
     `# SSL toolkit (is also dependency of openssh, git and others)` \
@@ -31,7 +31,10 @@ sudo pacman --sync --refresh --sysupgrade --needed "$@" \
     gcc \
     `# Go compiler` \
     go
-    
+then
+    echo "Failed!"
+    exit 1
+fi
 
 # Go dev support tools (but can be installed from VSCode or with "go get" command instead)
 #    `# Go basic support tools (goimports, guru, etc)` \
diff --git a/debian-upgrade b/debian-upgrade
--- a/debian-upgrade
+++ b/debian-upgrade
@@ -125,8 +125,8 @@ fi
 # On clean WSL install of Debian 10 (Buster) version 10.8 it is missing!
 echo
 echo "Ensuring latest version of wget is installed..."
-if ! sudo apt install wget ; then
-    echo "ERROR: Update command returned with error code $?"
+if ! sudo apt install wget; then
+    echo "ERROR: install command returned with error code $?"
     exit 1
 fi
 
@@ -175,7 +175,7 @@ else
     else
         # Run a simple package update for existing release
         echo "Updating packages..."
-        if ! sudo apt upgrade ; then
+        if ! sudo apt upgrade; then
             echo "ERROR: Upgrade command returned with error code $?"
             exit 1
         fi
@@ -233,4 +233,3 @@ if ! sudo apt clean ; then
     echo "WARNING: Cleanup of package cache failed with error code $?"
     exit 1
 fi
-
