Improvements to setup scripts

diff --git a/arch-upgrade b/arch-upgrade
--- a/arch-upgrade
+++ b/arch-upgrade
@@ -3,7 +3,7 @@
 # Update package database and upgrade packages to latest version.
 #
 # This is intended for regular updates, relying on cached package database
-# without forcing a referesh and upgrading but not downgrading packages.
+# without forcing a refresh and upgrading but not downgrading packages.
 # For a more thorough and intrusive full upgrade, use arch-upgrade-full.
 # The only differences between these two are that it forces update of package
 # database using double --refresh options, and allow downgrading package using
@@ -34,7 +34,8 @@
 # If necessary, sudo must be added to all pacman commands, exept the
 # "pacman -Qttdq" / "pacman --query --deps --unrequired --unrequired --quiet".
 # Remember to either do both --refresh (-y) and --sysupgrade (-u), or none of them,
-# at least never just --refresh (-y) which will easily lead to the partial upgrades syndrome!
+# at least never just --refresh (-y) which will easily lead to a bad state of partial
+# upgrades!
 #
 # NOTE: Assumes basic tools are already installed, including sudo.
 # Run script ./arch-setup first to ensure this!
@@ -43,7 +44,13 @@
 #
 # Update the package database if necessary.
 # Not forcing a refresh even if it appear to be up-to-date, could add another
-# --refresh to do that that.
+# --refresh to do that.
+#
+# Note that this is a bit bit dangerous to do without upgrading packages as
+# well, since it may lead to a bad state of partial upgrades, but it is
+# intentional because we want to install/upgrade the keyring package first,
+# before we upgrade all packages.
+#
 #
 echo
 echo "Ensuring package database is updated..."
@@ -68,6 +75,11 @@ echo
 echo "Ensuring latest keyring package is installed..."
 if ! sudo pacman --sync --needed "$@" archlinux-keyring; then
     echo "Failed!"
+    echo "NOTE: The package database was previously successfully updated, but due to this"
+    echo "error when attempting to install/upgrade the keyring package, existing packages"
+    echo "have not been upgraded! Make sure to repeat this script until it succeeds, at"
+    echo "least do not install any new packages before existing packages has been"
+    echo "successfully upgraded, or else you may get into a bad state of partial upgrades!"
     exit 1
 fi
 
@@ -84,6 +96,11 @@ echo
 echo "Upgrading any outdated packages..."
 if ! sudo pacman --sync --sysupgrade "$@"; then
     echo "Failed!"
+    echo "NOTE: The package database was previously successfully updated, but since the"
+    echo "upgrading of existing packages failed, make sure to repeat this script until it"
+    echo "succeeds, at least do not install any new packages before existing packages has"
+    echo "been successfully upgraded, or else you may get into a bad state of partial"
+    echo "upgrades!"
     exit 1
 fi
 
@@ -91,12 +108,22 @@ fi
 # Uninstall any unrequired packages left behind (orphans).
 # Considering packages that were not explicitly installed, but originally installed as a
 # dependency of other packages, even as an optional dependency due to the double --unrequired.
-# Note: This command will fail when none were found: "argument '-' specified with empty stdin."
 #
 echo
-echo "Cleaning up unrequired packages..."
-echo "* Note that when none are found it is expected to see \"error: argument '-' specified with empty stdin\""
-pacman --query --deps --unrequired --unrequired --quiet | sudo pacman --remove --nosave --recursive "$@" -
+echo "Searching for unrequired packages..."
+#echo "* Note that when none are found it is expected to see \"error: argument '-' specified with empty stdin\""
+#pacman --query --deps --unrequired --unrequired --quiet | sudo pacman --remove --nosave --recursive "$@" -
+if orphans=$(pacman --query --deps --unrequired --unrequired --quiet) && [ -n "$orphans" ]; then
+    echo "Removing unrequired packages..."
+    # This works, assuming default IFS lead to correct splitting of argument, and because in Arch:
+    # Package names can contain only alphanumeric characters and any of @, ., _, +, -. Names are not
+    # allowed to start with hyphens or dots. All letters should be lowercase.
+    if ! sudo pacman --remove --nosave --recursive "$@" $orphans; then
+        echo "Failed!"
+        exit 1
+    fi
+fi
+unset orphans
 
 #
 # Clean the package database (cache).
diff --git a/arch-upgrade-full b/arch-upgrade-full
--- a/arch-upgrade-full
+++ b/arch-upgrade-full
@@ -34,7 +34,8 @@
 # If necessary, sudo must be added to all pacman commands, exept the
 # "pacman -Qttdq" / "pacman --query --deps --unrequired --unrequired --quiet".
 # Remember to either do both --refresh (-y) and --sysupgrade (-u), or none of them,
-# at least never just --refresh (-y) which will easily lead to the partial upgrades syndrome!
+# at least never just --refresh (-y) which will easily lead to a bad state of partial
+# upgrades!
 #
 # NOTE: Assumes basic tools are already installed, including sudo.
 # Run script ./arch-setup first to ensure this!
@@ -43,6 +44,11 @@
 #
 # Force update the package database.
 # Will refresh even if it appear to be up-to-date, due to double --refresh.
+#
+# Note that this is a bit bit dangerous to do without upgrading packages as
+# well, since it may lead to a bad state of partial upgrades, but it is
+# intentional because we want to install/upgrade the keyring package first,
+# before we upgrade all packages.
 #
 echo
 echo "Forcing update of package database..."
@@ -67,6 +73,11 @@ echo
 echo "Ensuring latest keyring package is installed..."
 if ! sudo pacman --sync --needed "$@" archlinux-keyring; then
     echo "Failed!"
+    echo "NOTE: The package database was previously successfully updated, but due to this"
+    echo "error when attempting to install/upgrade the keyring package, existing packages"
+    echo "have not been upgraded! Make sure to repeat this script until it succeeds, at"
+    echo "least do not install any new packages before existing packages has been"
+    echo "successfully upgraded, or else you may get into a bad state of partial upgrades!"
     exit 1
 fi
 
@@ -85,6 +96,11 @@ echo
 echo "Performing full upgrade/downgrade of packages..."
 if ! sudo pacman --sync --sysupgrade --sysupgrade "$@"; then
     echo "Failed!"
+    echo "NOTE: The package database was previously successfully updated, but since the"
+    echo "upgrading of existing packages failed, make sure to repeat this script until it"
+    echo "succeeds, at least do not install any new packages before existing packages has"
+    echo "been successfully upgraded, or else you may get into a bad state of partial"
+    echo "upgrades!"
     exit 1
 fi
 
@@ -92,12 +108,22 @@ fi
 # Uninstall any unrequired packages left behind (orphans).
 # Considering packages that were not explicitly installed, but originally installed as a
 # dependency of other packages, even as an optional dependency due to the double --unrequired.
-# Note: This command will fail when none were found: "argument '-' specified with empty stdin."
 #
 echo
-echo "Cleaning up unrequired packages..."
-echo "* Note that when none are found it is expected to see \"error: argument '-' specified with empty stdin\""
-pacman --query --deps --unrequired --unrequired --quiet | sudo pacman --remove --nosave --recursive "$@" -
+echo "Searching for unrequired packages..."
+#echo "* Note that when none are found it is expected to see \"error: argument '-' specified with empty stdin\""
+#pacman --query --deps --unrequired --unrequired --quiet | sudo pacman --remove --nosave --recursive "$@" -
+if orphans=$(pacman --query --deps --unrequired --unrequired --quiet) && [ -n "$orphans" ]; then
+    echo "Removing unrequired packages..."
+    # This works, assuming default IFS lead to correct splitting of argument, and because in Arch:
+    # Package names can contain only alphanumeric characters and any of @, ., _, +, -. Names are not
+    # allowed to start with hyphens or dots. All letters should be lowercase.
+    if ! sudo pacman --remove --nosave --recursive "$@" $orphans; then
+        echo "Failed!"
+        exit 1
+    fi
+fi
+unset orphans
 
 #
 # Clean the package database (cache).
diff --git a/debian-upgrade b/debian-upgrade
--- a/debian-upgrade
+++ b/debian-upgrade
@@ -73,7 +73,7 @@
 #   again will retry the upgrade!
 #
 
-if ! cat /etc/os-release | grep -q '^ID=debian$'; then
+if ! grep -q '^ID=debian$' /etc/os-release; then
     echo "This is not a Debian system!"
     exit 1
 fi
@@ -106,8 +106,8 @@ fi
 echo "Looking up current release information..."
 RELEASE_CHANNEL=${1:-${RELEASE_CHANNEL:-stable}}
 echo "Channel: ${RELEASE_CHANNEL}"
-CURRENT_CODENAME=$(cat /etc/os-release | sed -rn 's/^VERSION="[0-9]+\s+\((.*)\)"/\1/p')
-[ -z "$CURRENT_CODENAME" ] && CURRENT_CODENAME=$(cat /etc/os-release | sed -rn 's/^PRETTY_NAME="Debian GNU\/Linux ([0-9]+ )?\(?([a-z]*)(\/[a-z]*)?\)?"/\2/p')
+CURRENT_CODENAME=$(sed -rn 's/^VERSION="[0-9]+\s+\((.*)\)"/\1/p' /etc/os-release)
+[ -z "$CURRENT_CODENAME" ] && CURRENT_CODENAME=$(sed -rn 's/^PRETTY_NAME="Debian GNU\/Linux ([0-9]+ )?\(?([a-z]*)(\/[a-z]*)?\)?"/\2/p' /etc/os-release)
 [ -z "$CURRENT_CODENAME" ] && echo "ERROR: Unable to find installed release codename" && exit 1
 CURRENT_VERSION=$(cat /etc/debian_version)
 [ -z "$CURRENT_VERSION" ] && echo "ERROR: Unable to find installed version info" && exit 1
@@ -116,8 +116,8 @@ echo "Installed version: $CURRENT_VERSION ($CURRENT_CODENAME)"
 # Start by updating package cache
 echo
 echo "Loading package index..."
-if ! sudo apt update ; then
-    echo "ERROR: Update command returned with error code $?"
+if ! sudo apt update; then
+    echo "ERROR: Update command failed"
     exit 1
 fi
 
@@ -126,17 +126,18 @@ fi
 echo
 echo "Ensuring latest version of wget is installed..."
 if ! sudo apt install wget; then
-    echo "ERROR: install command returned with error code $?"
+    echo "ERROR: Install command failed"
     exit 1
 fi
 
 # Fetch release information
 echo
 echo "Fetching latest release information..."
-LATEST_CODENAME=$(wget --quiet --timeout=10 --output-document=- http://deb.debian.org/debian/dists/${RELEASE_CHANNEL}/Release | grep '^Codename:' | cut -d' ' -f2)
+LATEST_RELEASE=$(wget --quiet --timeout=10 --output-document=- http://deb.debian.org/debian/dists/${RELEASE_CHANNEL}/Release)
+LATEST_CODENAME=$(echo "$LATEST_RELEASE" | grep '^Codename:' | cut -d' ' -f2)
 [ -z "$LATEST_CODENAME" ] && echo "ERROR: Unable to find latest release codename" && exit 1
 
-LATEST_VERSION=$(wget --quiet --timeout=10 --output-document=- http://deb.debian.org/debian/dists/${RELEASE_CHANNEL}/Release | grep '^Version:' | cut -d' ' -f2)
+LATEST_VERSION=$(echo "$LATEST_RELEASE" | grep '^Version:' | cut -d' ' -f2)
 # If latest version has not reached stable yet, it will not have a version number!
 #[ -z "$LATEST_VERSION" ] && echo "ERROR: Unable to find latest version major.minor" && exit 1
 [ -z "$LATEST_VERSION" ] && echo "Latest release version info not available, but this can be normal for releases newer than current stable"
@@ -148,8 +149,8 @@ if [ "$LATEST_CODENAME" = "$CURRENT_CODENAME" ]; then
     # No major version change.
     # Always run a simple package update just in case.
     echo "No major upgrade available, updating packages..."
-    if ! sudo apt upgrade ; then
-        echo "ERROR: Upgrade command returned with error code $?"
+    if ! sudo apt upgrade; then
+        echo "ERROR: Upgrade command failed"
         exit 1
     fi
     echo
@@ -162,7 +163,7 @@ else
     echo "Performing major upgrade from '${CURRENT_CODENAME}' to '${LATEST_CODENAME}'..."
 
     # Get current channel configured for main binary packages source.
-    CURRENT_SOURCE_CHANNEL=$(cat /etc/apt/sources.list | sed -rn 's/^deb\s+https?:\/\/deb.debian.org\/debian\s+([a-z]*)\s+main$/\1/p')
+    CURRENT_SOURCE_CHANNEL=$(sed -rn 's/^deb\s+https?:\/\/deb.debian.org\/debian\s+([a-z]*)\s+main$/\1/p' /etc/apt/sources.list)
     [ -z "$CURRENT_SOURCE_CHANNEL" ] && echo "FAILED: Unable to find current configured main package source version codename" && exit 1
 
     if [ "$CURRENT_SOURCE_CHANNEL" = "$LATEST_CODENAME" ]; then
@@ -176,7 +177,7 @@ else
         # Run a simple package update for existing release
         echo "Updating packages to latest version for current release..."
         if ! sudo apt upgrade; then
-            echo "ERROR: Upgrade command returned with error code $?"
+            echo "ERROR: Upgrade command failed"
             exit 1
         fi
         echo
@@ -194,14 +195,14 @@ else
             # repository the distributions are called <version>-security instead of <version>/updates.
             # Also changes from url security.debian.org/debian-security/ to just security.debian.org,
             # although this is not critical as they are just aliases to the same repository.
-            cat /etc/apt/sources.list | sed -r -e "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" -e "s/security.debian.org\/debian-security\/?\s+${LATEST_CODENAME}\/updates/security.debian.org ${LATEST_CODENAME}-security/"
+            sed -r -e "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" -e "s/security.debian.org\/debian-security\/?\s+${LATEST_CODENAME}\/updates/security.debian.org ${LATEST_CODENAME}-security/" /etc/apt/sources.list
         else
-            cat /etc/apt/sources.list | sed "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/"
+            sed "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" /etc/apt/sources.list
         fi
         echo
         read -p "Do you want to continue? [Y/n] " choice
         case "$choice" in
-        ""|y|Y ) ;;
+        ""|y|Y );;
         * ) echo "Aborted";exit 1;;
         esac
         if [ "${LATEST_CODENAME}" = "bullseye" ]; then
@@ -217,25 +218,33 @@ else
         fi
         echo
         echo "Reloading package index for changed source..."
-        if ! sudo apt update ; then
-            echo "ERROR: Update command returned with error code $?"
+        if ! sudo apt update; then
+            echo "ERROR: Update command failed"
             exit 1
         fi
     fi
-    # Run full upgrade from changed package source
-    # Note: Using 'apt-get upgrade' instead of 'apt upgrade' in this case, as recommended by debian!
-    if ! sudo apt-get upgrade || ! sudo apt full-upgrade ; then
-        echo "ERROR: Upgrade commands returned with error code $?"
+    # Run full upgrade from changed package source.
+    # This will not only install new dependencies, but will also remove
+    # currently installed packages if this is needed to upgrade the system
+    # as a whole.
+    # Note: Running upgrade before full-upgrade, and by using 'apt-get upgrade'
+    # instead of 'apt upgrade' in this case, as recommended by debian!
+    if ! sudo apt-get upgrade; then
+        echo "ERROR: Upgrade command failed"
         exit 1
     fi
-    if ! sudo apt --purge autoremove ; then
+    if ! sudo apt full-upgrade; then
+        echo "ERROR: Full-upgrade command failed"
+        exit 1
+    fi
+    if ! sudo apt --purge autoremove; then
         echo "WARNING: Cleanup of unused dependencies failed with error code $?"
         exit 1
     fi
 fi
 
 # Package cache cleanup
-if ! sudo apt clean ; then
+if ! sudo apt clean; then
     echo "WARNING: Cleanup of package cache failed with error code $?"
     exit 1
 fi
