Minor cleanup in shell scripts

diff --git a/arch-init-packages b/arch-init-packages
--- a/arch-init-packages
+++ b/arch-init-packages
@@ -18,8 +18,11 @@ if [ ${EUID:-$(id -u)} -ne 0 ]; then
     exit 1
 fi
 
+#
+# Force update the package database and upgrade/downgrade any modified packages.
+#
 echo
-echo "Updating package database and upgrading packages..."
+echo "Forcing update of package database and performing full upgrade/downgrade of packages..."
 if ! pacman --sync --refresh --refresh --sysupgrade --sysupgrade "$@"; then
     echo "Failed!"
     exit 1
@@ -88,6 +91,16 @@ if ! pacman --sync --needed "$@" \
     iproute2 \
     procps-ng
 then
+    echo "Failed!"
+    exit 1
+fi
+
+#
+# Cleanup package cache.
+#
+echo
+echo "Cleanup package cache..."
+if ! pacman --sync --clean "$@"; then
     echo "Failed!"
     exit 1
 fi
diff --git a/arch-install-dev-cpp-python-qt b/arch-install-dev-cpp-python-qt
--- a/arch-install-dev-cpp-python-qt
+++ b/arch-install-dev-cpp-python-qt
@@ -2,6 +2,12 @@
 #
 # Installs development tools, such as git, python and gcc.
 #
+# Also performs refresh of package database and upgrade of existing packages to ensure
+# we get latest versions. Runs with the -Syu option, which seems to be the recommended
+# approach for normal upgrades on arch, not -Syuu which may also downgrade packages. In
+# any case, remember to either do both --refresh (-y) and --sysupgrade (-u), or none of
+# them, at least never --refresh (-y) which will easily lead to the partial upgrades syndrome!
+#
 # Passes any script arguments to the pacman commands, so can execute script with
 # --noconfirm for instance to run non-interactively proceeding without prompting
 # user.
@@ -14,9 +20,8 @@
 # any wanted packages individually, and e.g. binutils will be included as depedency
 # of gcc. Also e.g. pyside2 includes libpng, libjpeg-turbo, icu etc.. used by others.
 #
-# NOTE: Remember to either do both --refresh (-y) and --sysupgrade (-u), or none of them,
-# at least never --refresh (-y) which will easily lead to the partial upgrades syndrome!
-#
+
+echo "Updating package database, upgrading existing packages, and installing new packages..."
 sudo pacman --sync --refresh --sysupgrade --needed "$@" \
     `# Diff command` \
     diffutils \
@@ -60,3 +65,10 @@ sudo pacman --sync --refresh --sysupgrade --needed "$@" \
 # # configuration file ~/.config/ccache/ccache.conf, so must run the script as the
 # # intended dev user and not root!
 # ccache --set-config max_size=500M
+
+echo
+echo "Cleaning package cache..."
+if ! pacman --sync --clean "$@"; then
+    echo "Failed!"
+    exit 1
+fi
diff --git a/arch-install-dev-go b/arch-install-dev-go
--- a/arch-install-dev-go
+++ b/arch-install-dev-go
@@ -3,6 +3,12 @@
 # Installs development environment for Go (golang), including gcc (for cgo),
 # and supporting tools such as git.
 #
+# Also performs refresh of package database and upgrade of existing packages to ensure
+# we get latest versions. Runs with the -Syu option, which seems to be the recommended
+# approach for normal upgrades on arch, not -Syuu which may also downgrade packages. In
+# any case, remember to either do both --refresh (-y) and --sysupgrade (-u), or none of
+# them, at least never --refresh (-y) which will easily lead to the partial upgrades syndrome!
+#
 # Passes any script arguments to the pacman commands, so can execute script with
 # --noconfirm for instance to run non-interactively proceeding without prompting
 # user.
@@ -10,9 +16,8 @@
 # NOTE: Assumes basic tools are already installed, including sudo.
 # Run script ./arch-init first to ensure this!
 #
-# NOTE: Remember to either do both --refresh (-y) and --sysupgrade (-u), or none of them,
-# at least never --refresh (-y) which will easily lead to the partial upgrades syndrome!
-#
+
+echo "Updating package database, upgrading existing packages, and installing new packages..."
 sudo pacman --sync --refresh --sysupgrade --needed "$@" \
     `# Diff command` \
     diffutils \
@@ -46,6 +51,12 @@ sudo pacman --sync --refresh --sysupgrade --needed "$@" \
 #    `# CMake build-system generator` \
 #    cmake \
 
-
 #    `# Alternative Go compiler, based on GCC` \
 #    gcc-go
+
+echo
+echo "Cleaning package cache..."
+if ! pacman --sync --clean "$@"; then
+    echo "Failed!"
+    exit 1
+fi
diff --git a/debian-upgrade b/debian-upgrade
--- a/debian-upgrade
+++ b/debian-upgrade
@@ -78,8 +78,8 @@ RELEASE_CHANNEL=${1:-${RELEASE_CHANNEL:-stable}}
 echo "Channel: ${RELEASE_CHANNEL}"
 
 if ! cat /etc/os-release | grep -q '^ID=debian$'; then
-	echo "This is not a Debian system!"
-	exit 1
+    echo "This is not a Debian system!"
+    exit 1
 fi
 echo "Checking versions..."
 
@@ -128,92 +128,92 @@ echo "Installed version: $CURRENT_VERSION ($CURRENT_CODENAME)"
 echo
 
 if [ "$LATEST_CODENAME" = "$CURRENT_CODENAME" ]; then
-	# No major version change.
-	# Always run a simple package update just in case.
-	echo "Updating packages..."
-	if ! sudo apt update || ! sudo apt upgrade ; then
-		echo "ERROR: Update commands returned with error code $?"
-		exit 1
-	fi
-	echo
-	if [ -z "$LATEST_VERSION" -o "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
-		echo "Your system is up to date: $CURRENT_VERSION ($CURRENT_CODENAME)"
-	else
-		echo "Your system was updated and is on latest release codename '${CURRENT_CODENAME}', but version '${CURRENT_VERSION}' differs from latest '${LATEST_VERSION}'"
-	fi
+    # No major version change.
+    # Always run a simple package update just in case.
+    echo "Updating packages..."
+    if ! sudo apt update || ! sudo apt upgrade ; then
+        echo "ERROR: Update commands returned with error code $?"
+        exit 1
+    fi
+    echo
+    if [ -z "$LATEST_VERSION" -o "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
+        echo "Your system is up to date: $CURRENT_VERSION ($CURRENT_CODENAME)"
+    else
+        echo "Your system was updated and is on latest release codename '${CURRENT_CODENAME}', but version '${CURRENT_VERSION}' differs from latest '${LATEST_VERSION}'"
+    fi
 else
-	echo "Performing major upgrade from '${CURRENT_CODENAME}' to '${LATEST_CODENAME}'..."
+    echo "Performing major upgrade from '${CURRENT_CODENAME}' to '${LATEST_CODENAME}'..."
 
-	# Get current channel configured for main binary packages source.
-	CURRENT_SOURCE_CHANNEL=$(cat /etc/apt/sources.list | sed -rn 's/^deb\s+https?:\/\/deb.debian.org\/debian\s+([a-z]*)\s+main$/\1/p')
-	[ -z "$CURRENT_SOURCE_CHANNEL" ] && echo "FAILED: Unable to find current configured main package source version codename" && exit 1
+    # Get current channel configured for main binary packages source.
+    CURRENT_SOURCE_CHANNEL=$(cat /etc/apt/sources.list | sed -rn 's/^deb\s+https?:\/\/deb.debian.org\/debian\s+([a-z]*)\s+main$/\1/p')
+    [ -z "$CURRENT_SOURCE_CHANNEL" ] && echo "FAILED: Unable to find current configured main package source version codename" && exit 1
 
-	if [ "$CURRENT_SOURCE_CHANNEL" = "$LATEST_CODENAME" ]; then
-		# Note: In this case we do not want to run simple package update (sudo apt update && sudo apt upgrade),
-		# because we want to use the full upgrade procedure since the package sources have changed!
-		echo "WARNING: Main package source are already configured for latest release, will not update it:"
-		echo
-		cat /etc/apt/sources.list
-		echo
-	else
-		# Run a simple package update for existing release
-		echo "Updating packages..."
-		if ! sudo apt update || ! sudo apt upgrade ; then
-			echo "ERROR: Update commands returned with error code $?"
-			exit 1
-		fi
-		echo
-		# Switch package source to new release
-		if [ "$CURRENT_SOURCE_CHANNEL" != "$CURRENT_CODENAME" ]; then
-			echo "WARNING: Main package source are currently configured to a release different from both current and latest release!"
-		fi
-		echo "Will perform a full-upgrade after changing /etc/apt/sources.list from this:"
-		echo
-		cat /etc/apt/sources.list
-		echo "To this:"
-		echo
-		if [ "${LATEST_CODENAME}" = "bullseye" ]; then
-			# Note: Additional change introduced with Debian 11 bullseye: In the security
-			# repository the distributions are called <version>-security instead of <version>/updates.
-			# Also changes from url security.debian.org/debian-security/ to just security.debian.org,
-			# although this is not critical as they are just aliases to the same repository.
-			cat /etc/apt/sources.list | sed -r -e "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" -e "s/security.debian.org\/debian-security\/?\s+${LATEST_CODENAME}\/updates/security.debian.org ${LATEST_CODENAME}-security/"
-		else
-			cat /etc/apt/sources.list | sed "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/"
-		fi
-		echo
-		read -p "Do you want to continue? [Y/n]" choice
-		case "$choice" in
-		""|y|Y ) ;;
-		* ) echo "Aborted";exit 1;;
-		esac
-		if [ "${LATEST_CODENAME}" = "bullseye" ]; then
-			if ! sudo sed -i -r -e "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" -e "s/security.debian.org\/debian-security\/?\s+${LATEST_CODENAME}\/updates/security.debian.org ${LATEST_CODENAME}-security/" /etc/apt/sources.list; then
-				echo "ERROR: Could not update /etc/apt/sources.list"
-				exit 1
-			fi
-		else
-			if ! sudo sed -i "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" /etc/apt/sources.list; then
-				echo "ERROR: Could not update /etc/apt/sources.list"
-				exit 1
-			fi
-		fi
-	fi
-	# Run full upgrade from changed package source
-	# Note: Using 'apt-get upgrade' instead of 'apt upgrade' in this case, as recommended by debian!
-	if ! sudo apt update || ! sudo apt-get upgrade || ! sudo apt full-upgrade ; then
-		echo "ERROR: Upgrade commands returned with error code $?"
-		exit 1
-	fi
-	if ! sudo apt --purge autoremove ; then
-		echo "WARNING: Cleanup of unused dependencies failed with error code $?"
-		exit 1
-	fi
+    if [ "$CURRENT_SOURCE_CHANNEL" = "$LATEST_CODENAME" ]; then
+        # Note: In this case we do not want to run simple package update (sudo apt update && sudo apt upgrade),
+        # because we want to use the full upgrade procedure since the package sources have changed!
+        echo "WARNING: Main package source are already configured for latest release, will not update it:"
+        echo
+        cat /etc/apt/sources.list
+        echo
+    else
+        # Run a simple package update for existing release
+        echo "Updating packages..."
+        if ! sudo apt update || ! sudo apt upgrade ; then
+            echo "ERROR: Update commands returned with error code $?"
+            exit 1
+        fi
+        echo
+        # Switch package source to new release
+        if [ "$CURRENT_SOURCE_CHANNEL" != "$CURRENT_CODENAME" ]; then
+            echo "WARNING: Main package source are currently configured to a release different from both current and latest release!"
+        fi
+        echo "Will perform a full-upgrade after changing /etc/apt/sources.list from this:"
+        echo
+        cat /etc/apt/sources.list
+        echo "To this:"
+        echo
+        if [ "${LATEST_CODENAME}" = "bullseye" ]; then
+            # Note: Additional change introduced with Debian 11 bullseye: In the security
+            # repository the distributions are called <version>-security instead of <version>/updates.
+            # Also changes from url security.debian.org/debian-security/ to just security.debian.org,
+            # although this is not critical as they are just aliases to the same repository.
+            cat /etc/apt/sources.list | sed -r -e "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" -e "s/security.debian.org\/debian-security\/?\s+${LATEST_CODENAME}\/updates/security.debian.org ${LATEST_CODENAME}-security/"
+        else
+            cat /etc/apt/sources.list | sed "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/"
+        fi
+        echo
+        read -p "Do you want to continue? [Y/n]" choice
+        case "$choice" in
+        ""|y|Y ) ;;
+        * ) echo "Aborted";exit 1;;
+        esac
+        if [ "${LATEST_CODENAME}" = "bullseye" ]; then
+            if ! sudo sed -i -r -e "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" -e "s/security.debian.org\/debian-security\/?\s+${LATEST_CODENAME}\/updates/security.debian.org ${LATEST_CODENAME}-security/" /etc/apt/sources.list; then
+                echo "ERROR: Could not update /etc/apt/sources.list"
+                exit 1
+            fi
+        else
+            if ! sudo sed -i "s/${CURRENT_CODENAME}/${LATEST_CODENAME}/" /etc/apt/sources.list; then
+                echo "ERROR: Could not update /etc/apt/sources.list"
+                exit 1
+            fi
+        fi
+    fi
+    # Run full upgrade from changed package source
+    # Note: Using 'apt-get upgrade' instead of 'apt upgrade' in this case, as recommended by debian!
+    if ! sudo apt update || ! sudo apt-get upgrade || ! sudo apt full-upgrade ; then
+        echo "ERROR: Upgrade commands returned with error code $?"
+        exit 1
+    fi
+    if ! sudo apt --purge autoremove ; then
+        echo "WARNING: Cleanup of unused dependencies failed with error code $?"
+        exit 1
+    fi
 fi
 
 # Package cache cleanup
 if ! sudo apt clean ; then
-	echo "WARNING: Cleanup of package cache failed with error code $?"
-	exit 1
+    echo "WARNING: Cleanup of package cache failed with error code $?"
+    exit 1
 fi
 
