Fix issue in debian upgrade script where it would not reload package index after changing sources.list

diff --git a/debian-upgrade b/debian-upgrade
--- a/debian-upgrade
+++ b/debian-upgrade
@@ -174,7 +174,7 @@ else
         echo
     else
         # Run a simple package update for existing release
-        echo "Updating packages..."
+        echo "Updating packages to latest version for current release..."
         if ! sudo apt upgrade; then
             echo "ERROR: Upgrade command returned with error code $?"
             exit 1
@@ -214,6 +214,12 @@ else
                 echo "ERROR: Could not update /etc/apt/sources.list"
                 exit 1
             fi
+        fi
+        echo
+        echo "Reloading package index for changed source..."
+        if ! sudo apt update ; then
+            echo "ERROR: Update command returned with error code $?"
+            exit 1
         fi
     fi
     # Run full upgrade from changed package source
