Fedora support changed to use standard container base images, and now also supports the minimal image with microdnf and without python preinstalled.

diff --git a/fedora-install-dev-cpp-python-qt b/fedora-install-dev-cpp-python-qt
--- a/fedora-install-dev-cpp-python-qt
+++ b/fedora-install-dev-cpp-python-qt
@@ -1,10 +1,38 @@
 #!/bin/sh
 #
-# Installs development tools, such as git, python and gcc.
+# Install script for C++ and related development tools, such as git, python and gcc.
+#
+# NOTE:
+# - Written for WSL import of docker root filesystem of Fedora 33 and 34,
+#   from Fedora Container Base image (with dnf) and Fedora Container Minimal
+#   Base image (with microdnf).
+# - Must be run by actual root user, not by use of sudo from regular user,
+#   (sudo is not installed by default in the Fedora Container Minimal Base image).
+# - Interactive! Will prompt user before doing any changes!
+# - Skips installation of documentation, by specifying --nodocs as command line
+#   argument. Standard base image has this configured as default with
+#   "tsflags=nodocs" in /etc/dns/dns.conf, but this is not supported by microdnf
+#   so for the minimal base image it must be added on command line.
 #
 
+# Verify running as root
+if [ ${EUID:-$(id -u)} -ne 0 ]; then
+    echo 'Please run this script as root'
+    exit 1
+fi
+
+# Figure out if we have dnf or microdnf (from the Fedora Container Minimal Base image)
+if hash dnf > /dev/null 2>&1; then
+    dnf=dnf
+elif hash microdnf > /dev/null 2>&1; then
+    dnf=microdnf
+else
+    echo 'Package manager dnf or microdnf not found'
+    exit 1
+fi
+
 echo "Installing packages..."
-if ! sudo dnf install \
+if ! $dnf --nodocs install \
     `# Diff command` \
     diffutils \
     `# SSL toolkit` \
@@ -59,10 +87,3 @@ fi
 # # configuration file ~/.config/ccache/ccache.conf, so must run the script as the
 # # intended dev user and not root!
 # ccache --set-config max_size=500M
-
-echo
-echo "Cleanup package cache..."
-if ! dnf clean packages; then
-    echo "Failed!"
-    exit 1
-fi
diff --git a/fedora-setup-locale b/fedora-setup-locale
--- a/fedora-setup-locale
+++ b/fedora-setup-locale
@@ -1,12 +1,13 @@
 #!/bin/sh
 #
 # Configure locale.
+#
 # In Fedora the locales are installed as regular packages with name prefix glibc-langpack.
 # There are also some higher order language support meta packages with name prefix "langpacks",
 # which ensures installation of translations, additional fonts and input methods, as well as
 # the locale via the appropriate glibc-langpack package.
 #
-# Fedora 34 has installed the following packages by default:
+# Fedora 34 standard base image has installed the following packages by default:
 # - glibc-minimal-langpack
 # - langpacks-en_GB
 #   - With dependencies: langpacks-core-en_GB, langpacks-core-font-en, fonts-filesystem, dejavu-sans-fonts
@@ -19,30 +20,54 @@
 #
 # The result should be that en_US.UTF-8 is automatically activated as the new locale, instead of C.UTF-8.
 #
+# NOTE:
+# - Written for WSL import of docker root filesystem of Fedora 33 and 34,
+#   from Fedora Container Base image (with dnf) and Fedora Container Minimal
+#   Base image (with microdnf).
+# - Must be run by actual root user, not by use of sudo from regular user,
+#   (sudo is not installed by default in the Fedora Container Minimal Base image).
+# - Interactive! Will prompt user before doing any changes!
+# - Skips installation of documentation, by specifying --nodocs as command line
+#   argument. Standard base image has this configured as default with
+#   "tsflags=nodocs" in /etc/dns/dns.conf, but this is not supported by microdnf
+#   so for the minimal base image it must be added on command line.
+#
 
-# Verify running as root (not relying on sudo which may not be installed yet).
+# Verify running as root
 if [ ${EUID:-$(id -u)} -ne 0 ]; then
     echo 'Please run this script as root'
     exit 1
 fi
 
+# Figure out if we have dnf or microdnf (from the Fedora Container Minimal Base image)
+if hash dnf > /dev/null 2>&1; then
+    dnf=dnf
+elif hash microdnf > /dev/null 2>&1; then
+    dnf=microdnf
+else
+    echo 'Package manager dnf or microdnf not found'
+    exit 1
+fi
+
 echo
 echo "Removing language support packages..."
-if ! sudo dnf remove langpacks-*; then
-    echo "Failed!"
-    exit 1
+# NOTE: Full version of dnf supports wildcards:
+#   if ! $dnf remove langpacks-*; then
+# but microdnf does not, so we query list of actual names instead
+packages=$(rpm -qa --queryformat '%{NAME} ' 'langpacks-*')
+if [ -n "$packages" ]; then
+    if ! $dnf remove $packages; then
+        echo "Failed!"
+        exit 1
+    fi
 fi
 
 echo
 echo "Installing english locale package..."
-if ! sudo dnf install glibc-langpack-en; then
-    echo "Failed!"
-    exit 1
-fi
-
-echo
-echo "Cleanup package cache..."
-if ! dnf clean packages; then
+# NOTE: Adding --nodocs to not install documentation. Standard base image has this
+# configured as default with "tsflags=nodocs" in /etc/dns/dns.conf, but this is
+# not supported by microdnf so for the minimal base image it must be added on command line.
+if ! $dnf --nodocs install glibc-langpack-en; then
     echo "Failed!"
     exit 1
 fi
diff --git a/fedora-setup-packages b/fedora-setup-packages
--- a/fedora-setup-packages
+++ b/fedora-setup-packages
@@ -2,23 +2,48 @@
 #
 # Perform full package upgrade, and installs some basic packages missing.
 #
+# NOTE:
+# - Written for WSL import of docker root filesystem of Fedora 33 and 34,
+#   from Fedora Container Base image (with dnf) and Fedora Container Minimal
+#   Base image (with microdnf).
+# - Must be run by actual root user, not by use of sudo from regular user,
+#   (sudo is not installed by default in the Fedora Container Minimal Base image).
+# - Interactive! Will prompt user before doing any changes!
+# - Skips installation of documentation, by specifying --nodocs as command line
+#   argument. Standard base image has this configured as default with
+#   "tsflags=nodocs" in /etc/dns/dns.conf, but this is not supported by microdnf
+#   so for the minimal base image it must be added on command line.
+# - Using "update" command even if has been superseded by "upgrade",
+#   because it wasn't until Fedora 34 that microdnf supported "upgrade" and
+#   in both dnf and microdnf "update" still works as an alias for "upgrade"!
+#
 
-# Verify running as root (not relying on sudo which may not be installed yet).
+# Verify running as root
 if [ ${EUID:-$(id -u)} -ne 0 ]; then
     echo 'Please run this script as root'
     exit 1
 fi
 
+# Figure out if we have dnf or microdnf (from the Fedora Container Minimal Base image)
+if hash dnf > /dev/null 2>&1; then
+    dnf=dnf
+elif hash microdnf > /dev/null 2>&1; then
+    dnf=microdnf
+else
+    echo 'Package manager dnf or microdnf not found'
+    exit 1
+fi
+
 echo
 echo "Upgrading packages..."
-if ! dnf upgrade --refresh; then
+if ! $dnf --nodocs --refresh update; then
     echo "Failed!"
     exit 1
 fi
 
 echo
 echo "Installing basic packages..."
-if ! sudo dnf install \
+if ! $dnf --nodocs install \
     findutils \
     unzip \
     wget \
@@ -27,13 +52,6 @@ if ! sudo dnf install \
     iproute \
     procps-ng
 then
-    echo "Failed!"
-    exit 1
-fi
-
-echo
-echo "Cleanup package cache..."
-if ! dnf clean packages; then
     echo "Failed!"
     exit 1
 fi
diff --git a/fedora-upgrade b/fedora-upgrade
--- a/fedora-upgrade
+++ b/fedora-upgrade
@@ -1,13 +1,28 @@
 #!/bin/sh
 #
-# Update script for Fedora.
+# Upgrade script to update packages to latest version, and optionally upgrade
+# the entire release to a newer major version.
 #
-# This script will look-up the current installed and the latest available stable release versions.
-# A release version number to upgrade to can be specified as argument, if not it defaults to latest.
-# If current is already at the specified version then a simple package upgrade is performed.
-# If on a different version then a major upgrade is performed.
+# This script will look-up the current installed and the latest available stable
+# release versions. A release version number to upgrade to can be specified as
+# argument, if not it defaults to latest. If current is already at the specified
+# version then a simple package upgrade is performed. If on a different version
+# then a major upgrade is performed.
 #
 # NOTE:
+# - Written for WSL import of docker root filesystem of Fedora 33 and 34,
+#   from Fedora Container Base image (with dnf) and Fedora Container Minimal
+#   Base image (with microdnf).
+# - Must be run by actual root user, not by use of sudo from regular user,
+#   (sudo is not installed by default in the Fedora Container Minimal Base image).
+# - Interactive! Will prompt user before doing any changes!
+# - Skips installation of documentation, by specifying --nodocs as command line
+#   argument. Standard base image has this configured as default with
+#   "tsflags=nodocs" in /etc/dns/dns.conf, but this is not supported by microdnf
+#   so for the minimal base image it must be added on command line.
+# - Using "update" command even if has been superseded by "upgrade",
+#   because it wasn't until Fedora 34 that microdnf supported "upgrade" and
+#   in both dnf and microdnf "update" still works as an alias for "upgrade"!
 # - Be careful if there are more than one major version between the current
 #   and the target version. You sould probably upgrade one version at a time.
 #   Specify version number as command line argument to control this.
@@ -17,18 +32,33 @@
 # - Read the upgrade guide to see recommended steps to be performed, and if
 #   there are special considerations for the specific release version:
 #   https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-online/
-# - Script is interactive! Will prompt user before doing any changes!
 #
+
+# Verify running as root
+if [ ${EUID:-$(id -u)} -ne 0 ]; then
+    echo 'Please run this script as root'
+    exit 1
+fi
 
 if ! cat /etc/os-release | grep -q '^ID=fedora$'; then
     echo "This is not a Fedora system!"
     exit 1
 fi
 
+# Figure out if we have dnf or microdnf (from the Fedora Container Minimal Base image)
+if hash dnf > /dev/null 2>&1; then
+    dnf=dnf
+elif hash microdnf > /dev/null 2>&1; then
+    dnf=microdnf
+else
+    echo 'Package manager dnf or microdnf not found'
+    exit 1
+fi
+
 # Perform a normal package upgrade
 # Alternatives: Force sync of all repositories with --refresh? Only perform upgrade-minimal?
 echo "Upgrading packages..."
-if ! sudo dnf upgrade; then
+if ! $dnf --nodocs update; then
     echo "Failed!"
     exit 1
 fi
@@ -50,30 +80,17 @@ if [ -n "$TARGET_RELEASE" ]; then
 else
     echo "Target release argument not specified, finding latest release..."
     # Make sure wget is installed, on clean WSL install of Fedora 34 it is missing!
-    echo "Ensuring wget is installed..."
-    if ! sudo dnf install wget; then
-        echo "ERROR: Update command returned with error code $?"
-        exit 1
+    if ! hash wget > /dev/null 2>&1; then
+        echo "Installing wget, need it for requesting release info..."
+        if ! $dnf --nodocs install wget; then
+            echo "ERROR: Install command returned with error code $?"
+            exit 1
+        fi
     fi
     LATEST_RELEASE=$(wget --quiet --timeout=10 --output-document=- https://dl.fedoraproject.org/pub/fedora/linux/releases/ | sed --quiet --regexp-extended 's/^.*<a href="([0-9]+)\/">.*$/\1/p' | sort --numeric-sort | tail -1)
     [ -z "$LATEST_RELEASE" ] && echo "ERROR: Unable to find latest release version" && exit 1
     echo "Target/latest release: $LATEST_RELEASE"
     TARGET_RELEASE=$LATEST_RELEASE
-fi
-
-# Always run a simple package update just in case.
-echo
-echo "Updating packages..."
-if ! sudo dnf upgrade; then
-    echo "ERROR: Upgrade command returned with error code $?"
-    exit 1
-fi
-
-echo
-echo "Cleanup package cache..."
-if ! dnf clean packages; then
-    echo "Failed!"
-    exit 1
 fi
 
 if [ "$TARGET_RELEASE" = "$CURRENT_RELEASE" ]; then
@@ -87,38 +104,44 @@ else
     echo "as separate upgrades instead!"
 
     echo
-    read -p "Do you want to continue? [Y/n]" choice
+    read -p "Do you want to continue? [Y/n] " choice
     case "$choice" in
     ""|y|Y ) ;;
     * ) echo "Aborted";exit 1;;
     esac
 
-    echo
-    echo "Removing unused dependencies..."
-    if ! sudo dnf autoremove; then
-        echo "Failed!"
-        exit 1
+    # Delete unused dependencies
+    # NOTE: The microdnf tool does not support the autoremove command.
+    # NOTE: Standard container images (including the minimal) has configured clean_requirements_on_remove=True
+    # which means every package remove in reality is an autoremove, so this should do nothing!
+    if [ "$dnf" != "microdnf" ]; then
+        echo
+        echo "Removing unused dependencies..."
+        if ! $dnf autoremove; then
+            echo "Failed!"
+            exit 1
+        fi
     fi
 
     echo
-    echo "Cleaning package cache..."
-    if ! sudo dnf clean all; then
+    echo "Cleaning cache and metadata..."
+    if ! $dnf clean all; then
         echo "Failed!"
         exit 1
     fi
 
     echo
     echo "Upgrading to new release..."
-    if ! dnf --releasever=${TARGET_RELEASE} --setopt=deltarpm=false distro-sync; then
-        echo "Failed!"
-        exit 1
-    fi
-
-    echo
-    echo "Cleanup package cache..."
-    if ! dnf clean packages; then
-        echo "Failed!"
-        exit 1
+    if [ "$dnf" = "microdnf" ]; then
+        if ! $dnf --nodocs --releasever=${TARGET_RELEASE} update; then
+            echo "Failed!"
+            exit 1
+        fi
+    else
+        if ! $dnf --nodocs --releasever=${TARGET_RELEASE} --setopt=deltarpm=false distro-sync; then
+            echo "Failed!"
+            exit 1
+        fi
     fi
 
     echo "Looking up new release information..."
